spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_01?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 5201314qv
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
